Wildlife/urls.py
from django.contrib import admin
from django.urls import path,include
from subscribe import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Sanctuary.urls')),
    path('sendemail', views.subscribe_func, name = 'subscribe'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Sanctuary/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.contrib.sessions.models import Session
import datetime

# Create your models here.
class blog(models.Model):

    content= models.TextField()
    title= models.CharField(max_length=122, null=True)
    created = models.DateTimeField(auto_now_add=True)
    image = models.FileField(upload_to='images/')

    def __str__(self):
        return self.title

class BookingForm(models.Model):
    GENDER = (
        ('m', 'Male'),
        ('f', 'Female'),
    )
    
    PACKAGES = (
        ('Couple Pack','Couple Pack'),
        ('Family Pack','Family Pack'),
        ('Custom Pack','Custom Pack'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    firstName = models.CharField(max_length=30)
    lastName = models.CharField(max_length=30)
    age = models.IntegerField(default=5)
    phone_number = models.CharField(max_length=12)
    country = models.CharField(max_length=20)
    gender = models.CharField(max_length=1, choices=GENDER)
    packs = models.CharField(max_length=11,choices=PACKAGES, default='')
    created = models.DateTimeField(auto_now_add=True)
    date = models.DateField(blank=True, null=True)

    def __str__(self):
        return str((self.user)) + ' - ' + str((self.phone_number))

class Category(models.Model):
    categoryName = models.CharField(max_length=20)

    def __str__(self):
        return self.categoryName

class Product(models.Model):
    productTitle = models.CharField(max_length=120)
    productDisp = models.ImageField(default='')
    productDesc = models.TextField()
    productPrice = models.IntegerField(default=200)
    productOffer = models.IntegerField(null=True, blank=True)
    productCategory = models.ForeignKey(Category, on_delete=models.CASCADE, default=1, related_name='cat')

    def __str__(self):
        return self.productTitle

    @staticmethod
    def getProductByID(ids):
        return Product.objects.filter(id__in = ids)

class FeaturedProduct(models.Model):
    featuredProduct = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product')

    def __str__(self):
        return self.featuredProduct.productTitle

class order(models.Model):
    Customer = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='producted')
    quantity = models.IntegerField(default=1)
    price = models.IntegerField()
    address = models.CharField(max_length=50, default='', blank=True)
    phone = models.CharField(max_length=50, default='', blank=True)
    date = models.DateField(default=datetime.datetime.today)
    completed = models.BooleanField(default=False)

    def placeOrder(self):
        return self.save()

    def __str__(self):
        c=self.Customer
        p=self.product
        return (('%s' % c)  + ' : ' + ('%s' % p))

    def getCustomerId(Customer_id):
        return order.objects.filter(Customer=Customer_id)

class NewsCategory(models.Model):
    category_news = (
        # ('News','News'),
        ('WildCats','WildCats'),
        ('Animals','Animals'),
        ('Volunteering','Volunteering'),
    )
    categoryTitle = models.CharField(max_length=20, choices=category_news)

    def __str__(self):
        return self.categoryTitle

class News(models.Model):
    newsTitle = models.CharField(max_length=120)
    newsContent = models.TextField(default='')
    created = models.DateTimeField(auto_now_add=True)
    image = models.FileField(upload_to='images/')
    Category = models.ForeignKey(NewsCategory, on_delete=models.CASCADE, blank=True, null=True, related_name='category')

    def __str__(self):
        return self.newsTitle

class Partners(models.Model):
    Partnername = models.CharField(max_length=30)
    Partnerimage = models.FileField(upload_to='images/')
    Partnerlink = models.URLField(default='')

    def __str__(self):
        return self.Partnername
    
class Donate(models.Model):
    fname = models.CharField(max_length=20)
    lname = models.CharField(max_length=20)
    phone = models.CharField(max_length=12)
    email = models.EmailField(max_length=254)
    address = models.TextField(default='')
    comment = models.TextField(default='')
    amount = models.PositiveIntegerField(default=50)

    def __str__(self):
        return self.fname

class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    subject = models.TextField(max_length=54)
    message = models.TextField(max_length=254)
    
    def __str__(self):
        return self.name

class Statistic(models.Model):
    name = models.CharField(max_length=20)
    count = models.IntegerField(default=1)

    def __str__(self):
        return (str(self.name) + ' - ' + str(self.count))

templates/base.html
{% load static %}

<!-- responsive -->
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <script src="/cdn-cgi/apps/head/3ts2ksMwXvKRuG480KNifJ2_JNM.js"></script>
  <link rel="icon" href="images/favicon.ico" type="image/x-icon">
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lato:300,400,500,700,900%7CRoboto:400">
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/ecom.css' %}">
  <script src="https://use.fontawesome.com/0bc5669de5.js"></script>
</head>

<div class="preloader">
  <div class="preloader-body">
    <div class="cssload-container">
      <div class="cssload-speeding-wheel"></div>
    </div>
    <p>Loading...</p>
  </div>
</div>

  <div class="page">
    <!-- Page Header-->
    <header class="section page-header">
      <!-- RD Navbar-->
      <div class="rd-navbar-wrap">
        <nav style="background: #444141;" class="rd-navbar rd-navbar-aside">
          <div class="rd-navbar-main-outer">
            <div class="rd-navbar-main">
              <!-- RD Navbar Panel-->
              <div class="rd-navbar-panel">
                <!-- RD Navbar Toggle-->
                <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                <!-- RD Navbar Brand-->
                <div class="rd-navbar-brand"><a href="{% url 'home' %}"><img class="brand-logo-light"
                      src="{% static 'images/logo-inverse-181x50.png' %}" alt="" width="181" height="50"
                      srcset="images/logo-inverse-362x100.png 2x" /></a></div>
                <div class="block-right">
                  <ul class="list-inline nav-list">
                    <li class="list-inline-item"><a href="{% url 'ticketbooking' %}">Book now</a></li>
                    <li class="list-inline-item"><a href="{% url 'ecom' %}">Shop!</a></li>
                    <li class="list-inline-item"><a href="{% url 'news' %}">What's New</a></li>
                    <li class="list-inline-item">
                      <form action="{% url 'search' %}" method="post" autocomplete="off">
                        {% csrf_token %}
                        <div class="searchNavForm">
                          <input type="text" placeholder="Search" name='value'>
                          <button type="submit" class="navSearchBtn"><i class="fas fa-search"></i></button>
                        </div>
                      </form>
                    </li>
                    {% if user.is_authenticated %}
                      <li class="list-inline-item"><a href="{% url 'finalOrder' %}">Order</a></li>
                    {% endif %}
                    {% if request.session.cart %}
                    <li class="list-inline-item">
                      <a href="{% url 'cartProducts' %}">Cart</a>
                      <span class="badge badge-info" style="cursor: default;" aria-readonly="">{{ request.session.cart.keys|length }}</span>
                    </li>
                    {% endif %}
                  </ul>
                  <div class="rd-navbar-aside-outer rd-navbar-collapse">
                    <div class="rd-navbar-aside">
                      <ul class="list-inline header-soc-list">
                        {% if user.is_authenticated %}
                        <li><a class="icon" href="#">Hi, {{ user.username }}!</a></li>
                        <li><a class="icon" href="{% url 'userslogout' %}">Logout</a></li>
                        {% else %}
                        <li><a class="icon" href="{% url 'Signin' %}">Login</a></li>
                        <li><a class="icon" href="{% url 'Signup' %}">Sign up</a></li>
                        {% endif %}
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <div class="rd-navbar-main-element">
                <div class="rd-navbar-nav-wrap">
                  <!-- RD Navbar Nav-->
                  <ul class="rd-navbar-nav">
                    <li class="rd-nav-item"><a class="rd-nav-link" href="{% url 'blogs' %}">Blogs</a>
                    </li>
                    <li class="rd-nav-item"><a class="rd-nav-link" href="{% url 'aboutus' %}">About us</a>
                    </li>
                    <li class="rd-nav-item"><a class="rd-nav-link" href="{% url 'OurTeams' %}">Our Team</a>
                    </li>
                    <li class="rd-nav-item"><a class="rd-nav-link" href="{% url 'Partners' %}">Partners</a>
                    </li>
                    <li class="rd-nav-item"><a class="rd-nav-link" href="{% url 'ContactUs' %}">Contacts</a>
                    </li>
                    <li class="rd-nav-item"><a class="rd-nav-link" href="{% url 'donate' %}">Donate</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </nav>
      </div>
    </header>
{% block content %}
{% endblock %}
<!-- Page Footer-->
<footer class="section footer-minimal context-dark">
    <div class="container wow-outer">
      <div class="wow fadeIn">
        <div class="row row-30 row-xl-50">
          <div class="col-12"><a class="footer-brand" href="index.html"><img src="{% static 'images/logo-inverse-181x50.png' %}"
                alt="" width="181" height="50" srcset="images/logo-inverse-362x100.png 2x" /></a></div>
          <div class="col-12">
            <ul class="footer-minimal-nav">
              <li><a href="{% url 'aboutus' %}">About</a></li>
              <li><a href="{% url 'news' %}">News</a></li>
              <li><a href="{% url 'ContactUs' %}">contacts </a></li>
              <li><a href="{% url 'donate' %}">Donate</a></li>
            </ul>
          </div>
          <div class="col-12">
            <ul class="social-list">
              <li><a class="icon icon-sm icon-circle icon-circle-md icon-bg-white fa-facebook" href="#"></a></li>
              <li><a class="icon icon-sm icon-circle icon-circle-md icon-bg-white fa-instagram" href="#"></a></li>
              <li><a class="icon icon-sm icon-circle icon-circle-md icon-bg-white fa-twitter" href="#"></a></li>
              <li><a class="icon icon-sm icon-circle icon-circle-md icon-bg-white fa-youtube-play" href="#"></a></li>
            </ul>
          </div>
        </div>
        <p class="rights"><span>&copy;&nbsp; </span><span
            class="copyright-year"></span><span>&nbsp;</span><span>Wildlife</span><span>.&nbsp;</span><span>All Rights
            Reserved</span><span>.&nbsp;</span><a href="#">Privacy Policy</a></p>
      </div>
    </div>
  </footer>

  
<div class="snackbars" id="form-output-global"></div>
<script src="{% static 'js/core.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>

templates/cartProducts.html
{% extends "base.html" %}

{% load static %}

{% block content %}

{% load cart %}

<link rel="stylesheet" href="{% static 'css/ecom.css' %}">

<div class="">
    <h2 class="marginFix">Your Items:</h2>
</div>

<div class="">
    <table class="border tableSubFlex m-4 mt-5 p-5" style="width: 65%;" cellpadding="2">
        <tbody>
            <tr class="headText">
                <td><b class="fontSizeInc">S.No.</b></td>
                <td><b class="fontSizeInc">Title</b></td>
                <td><b class="fontSizeInc">Image</b></td>
                <td><b class="fontSizeInc">Quantity</b></td>
                <td><b class="fontSizeInc">Price</b></td>
                <td><b class="fontSizeInc">Total</b></td>
                <td><b class="fontSizeInc">Remove</b></td>
            </tr>
            {% for i in Cart %}
            <tr class="cartProducts">
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'product' i.id %}" class="productTitleCart">{{ i.productTitle }}</a></td>
                <td><img class="cartImgProduct" src="{{ i.productDisp.url }}" alt=""></td>
                <td>{{ i|cart_quantity:request.session.cart }}</td>
                <td>${{ i.productPrice }}</td>
                <td>${{ i|totalPrice:request.session.cart }}</td>
                <td>
                    <form action="#" class="" method="POST">
                        {% csrf_token %}
                        <input hidden type="text" name="product_idd" value="{{ i.id }}">
                        <input type="submit" value='&#10060;' class="quantityBtn" readonly>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <td><hr style="width: 65%; float: right;"></td>
            <td><hr></td>
            <td><hr></td>
            <td><hr></td>
            <td><hr></td>
            <td><hr></td>
            <td class="">
                <button data-toggle="modal" data-target="#exampleModalCenter" style="text-transform: uppercase; width: 160px" class="addToCart">Check Out</button>
            </td>
        </tfoot>
        <tfoot class="totalCart headText">
            <th></th>
            <th></th>
            <th colspan=""><b>Total:</b></th>
            <th colspan="2"></th>
            <th><b>${{ Cart|totalPriceCart:request.session.cart }}</b></th>
            <th></th>
        </tfoot>
    </table>

    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Checkout</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            {% if user.is_authenticated %}
            <form action="{% url 'loginCheckout' %}" id="myFormSubmit" method="post">
                {% if not user.is_authenticated %}
                <h4 class="text-center mb-2">You need to login first</h4>
                {% endif %}
                {% csrf_token %}
                <div class="form-group">
                <label for="">Address</label>
                <input type="text" name="address" id="" class="form-control" placeholder="" aria-describedby="helpId">
                </div>
                <div class="form-group">
                    <label for="">Phone</label>
                    <input type="text" name="phone" id="" class="form-control" placeholder="" aria-describedby="helpId">
                </div>
                <div class="submit-btn">
                    <div style="width: 20% !important;" id="paypal-button-container"></div>

                    <!-- Include the PayPal JavaScript SDK -->
                    <script
                        src="https://www.paypal.com/sdk/js?client-id=AcK29cNvZ7dD5zShYcvy0DIbSABOYNdRJK7AR8hGnk0bgLnmqNEvfGPu_b8Ri83WaQmsXPe61YvtP51d&currency=USD">
                    </script>

                    <script>
                        // Render the PayPal button into #paypal-button-container
                        paypal.Buttons({
                            // Set up the transaction
                            createOrder: function (data, actions) {
                                return actions.order.create({
                                    purchase_units: [{
                                        amount: {
                                            value: '{{ Cart|totalPriceCart:request.session.cart }}'
                                        }
                                    }]
                                });
                            },
                            // Finalize the transaction
                            onApprove: function (data, actions) {
                                return actions.order.capture().then(function (details) {
                                    // Show a success message to the buyer
                                    alert('Transaction completed by ' + details.payer.name
                                        .given_name + '!');
                                    document.getElementById("myFormSubmit").submit();
                                });
                            }
                        }).render('#paypal-button-container');
                    </script>
                </div>
            </form>
            {% else %}
            <div class="text-center">Please signin/signup to checkout!</div>
            <br>
            <div class="checkoutBtnFix">
                <a href="{% url 'Signin' %}" class="btn btn-primary" class="text-center">Signin</a>
                <a href="{% url 'Signup' %}" class="btn btn-primary"  class="text-center">Signup</a>
            </div>
            {% endif %}
        </div>
        </div>
    </div>
</div>

</div>
{% endblock %}

templates/contact.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}

{% load static %}
<html class="wide wow-animation" lang="en">
<head>
    <title>Contacts</title>
    <style>
        .ie-panel {
            display: none;
            background: #212121;
            padding: 10px 0;
            box-shadow: 3px 3px 5px 0 rgba(0, 0, 0, .3);
            clear: both;
            text-align: center;
            position: relative;
            z-index: 1;
        }

        html.ie-10 .ie-panel,
        html.lt-ie-10 .ie-panel {
            display: block;
        }
    </style>
</head>

<body>
    <div class="ie-panel"><a href="https://windows.microsoft.com/en-US/internet-explorer/"><img
                src="images/ie8-panel/warning_bar_0000_us.jpg" height="42" width="820"
                alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a>
    </div>
    
    <div class="page">
        
        <section class="parallax-container" data-parallax-img="https://images.unsplash.com/photo-1444746715669-8558bd94fa7b?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1237&q=80">
            <div class="parallax-content breadcrumbs-custom context-dark">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-12 col-lg-9">
                            <h2 class="breadcrumbs-custom-title">Contacts</h2>
                            <ul class="breadcrumbs-custom-path">
                                <li><a href="index.html">Home</a></li>
                                <li class="active">Contacts</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="section section-lg text-center bg-default">
            <div class="container">
                <div class="row row-50">
                    <div class="col-md-6 col-lg-4">
                        <div class="box-icon-classic box-contact-info">
                            <div class="box-icon-inner decorate-triangle"><span
                                    class="icon-lg-big linearicons-phone-incoming"></span></div>
                            <div class="box-icon-caption">
                                <h4><a href="tel:#">1-800-123-1234</a></h4>
                                <p>You can call us anytime</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-4">
                        <div class="box-icon-classic box-contact-info">
                            <div class="box-icon-inner decorate-circle"><span
                                    class="icon-lg-big linearicons-map2"></span></div>
                            <div class="box-icon-caption">
                                <h4><a href="#">Inside Wildlife, Model Town</a></h4>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-4">
                        <div class="box-icon-classic box-contact-info">
                            <div class="box-icon-inner decorate-rectangle"><span
                                    class="icon-lg-big linearicons-paper-plane"></span></div>
                            <div class="box-icon-caption">
                                <h4><a href="mailto:#">wildlifebusiness@gmail.com</a></h4>
                                <p>Feel free to email us your questions</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Contact us-->
        <section class="section section-lg bg-gray-1 text-center">
            <div class="container">
                <div class="row justify-content-md-center">
                    <div class="col-md-9 col-lg-7">
                        <h3>Get In Touch</h3>
                        <!-- RD Mailform-->
                        <form class="rd-form" id="submit" data-form-output="form-output-global" data-form-type="contact"
                            method="POST" action="{% url 'savecontact' %}">
                            {% csrf_token %}
                            <div class="form-wrap">
                                <input class="form-input" id="contact-name" type="text" name="name"
                                    data-constraints="@Required">
                                <label class="form-label" for="contact-name">Name</label>
                            </div>
                            <div class="form-wrap">
                                <input class="form-input" id="contact-email" type="email" name="email"
                                    data-constraints="@Email @Required">
                                <label class="form-label" for="contact-email">Email</label>
                            </div>
                            <div class="form-wrap">
                                <input class="form-input" id="contact-subject" type="text" name="subject"
                                    data-constraints="@Required">
                                <label class="form-label" for="contact-subject">Subject</label>
                            </div>
                            <div class="form-wrap">
                                <label class="form-label" for="contact-message"> Message</label>
                                <textarea class="form-input" id="contact-message" name="message"
                                    data-constraints="@Required"></textarea>
                            </div>
                            <div class="row justify-content-center">
                                <div class="col-12 col-sm-7 col-lg-5">
                                    <button class="button button-block button-lg button-primary"
                                        type="submit">Send</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>

    </div>
</body>
</html>
{% endblock %}

templates/newscategory.html
{% extends "base.html" %}

{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/ecom.css' %}">
    <title>NewsCategory</title>
</head>
<body>
    
        {% for i in category %}
        <div class="news">
            <div class="news_head">
                <div class="news_img">
                   <img src="{{ i.image.url }}" alt="" />
                </div>
            
                <div class="news_desc">
                    <div class="news_title">
                        <p>{{ i.newsTitle }}</p>
                    </div>
                    <p style="text-align: left;">{{ i.newsContent|truncatechars:50 }}</p>
                    <p>{{ i.created }}</p>
                    <a href="{% url 'readnews' i.id %}" role="button">Continue Reading</a>
                </div>
            </div>
        </div>
        {% endfor %}
    
</body>
</html>


{% endblock %}

templates/ticketbooking.html
{% extends 'base.html' %}
{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/ecom.css' %}">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Booking</title>

<body style="background: transparent;">

    <div class=""></div>
    <video autoplay muted loop class="videoBG">
        <source src="{% static 'videos/bg3.mp4' %}" type="video/mp4">
    </video>
    <div class="containerr" style="background: transparent;">
        <form action="{% url 'booked' %}" id="myFormSubmit" method="POST" class="ticketForm" autocomplete="off">
            {% csrf_token %}
            <h2 style="color: #fff;">Book Your Ticket</h2>
            <div class="">
                <div class="common">
                    <span>
                        <label for="id_first_name">First name:</label>
                        <input type="text" required name="firstName" maxlength="30" id="id_first_name" class="hi">
                    </span>

                    <span>
                        <label for="id_last_name">Last name:</label>
                        <input type="text" required name="lastName" maxlength="150" id="id_last_name" class="hi">
                    </span>
                </div>
            </div>
            <div class="">
                <div class="common">
                    <span>
                        <label for="id_age">Age:</label>
                        <input type="number" required name="age" value="18" min="18" required="" class="hi" id="id_age">
                    </span>

                    <span class="selectTicket">
                        <label for="id_gender">Gender:</label>
                        <select name="gender" required id="id_gender" data-select2-id="id_gender" tabindex="0"
                            class="hi" aria-hidden="false">
                            <option value="m" data-select2-id="5">Male</option>
                            <option value="f" data-select2-id="6">Female</option>
                        </select>
                    </span>
                </div>
            </div>
            <div class="">
                <div class="common">
                    <span>
                        <label for="id_phone_number">Phone number:</label>
                        <input type="number" name="phone_number" maxlength="12" required="" id="id_phone_number"
                            class="hi">
                    </span>

                    <span>
                        <label for="id_country">Country:</label>
                        <input type="text" name="country" maxlength="20" required="" id="id_country" class="hi">
                    </span>
                </div>
            </div>
            <div class="">
                <div class="common">
                    <span class="selectTicket selectPack">
                        <label for="id_packs">Select a Pack:</label>
                        <select name="packs" required id="id_packs" data-select2-id="id_packs" tabindex="-1"
                            class="select2-hidden-accessible" aria-hidden="true" style="appearance: none;">
                            <option value="Couple Pack" data-select2-id="4">Couple Pack</option>
                            <option value="Family Pack" data-select2-id="12">Family Pack</option>
                            <option value="Custom Pack" data-select2-id="13">Custom Pack</option>
                        </select>
                    </span>
                </div>
            </div>
            <div class="">
                <div class="dateStyleBooking">
                    <label for="id_date" style="width: auto; margin-bottom: 10px;">Date:</label>
                    <input type="date" class="hi" required min="{{ date|date:"Y-m-d" }}" name="date" id="id_date">
                </div>
            </div>
            <div class="bookNowBtn">
                <div class="submit-btn">
                    <div style="width: 20% !important;" id="paypal-button-container"></div>

                    <!-- Include the PayPal JavaScript SDK -->
                    <script
                        src="https://www.paypal.com/sdk/js?client-id=AcK29cNvZ7dD5zShYcvy0DIbSABOYNdRJK7AR8hGnk0bgLnmqNEvfGPu_b8Ri83WaQmsXPe61YvtP51d&currency=USD">
                    </script>

                    <script>
                        // Render the PayPal button into #paypal-button-container
                        paypal.Buttons({
                            // Set up the transaction
                            createOrder: function (data, actions) {
                                return actions.order.create({
                                    purchase_units: [{
                                        amount: {
                                            value: '50'
                                        }
                                    }]
                                });
                            },
                            // Finalize the transaction
                            onApprove: function (data, actions) {
                                return actions.order.capture().then(function (details) {
                                    // Show a success message to the buyer
                                    alert('Transaction completed by ' + details.payer.name
                                        .given_name + '!');
                                    document.getElementById("myFormSubmit").submit();
                                });
                            }
                        }).render('#paypal-button-container');
                    </script>
                </div>
            </div>
        </form>
    </div>
</body>
{% endblock %}